# This file was auto-generated by Fern from our API Definition.

import typing

import httpx


class BaseClientWrapper:
    def __init__(self, *, custom_auth_scheme: str):
        self.custom_auth_scheme = custom_auth_scheme

    def get_headers(self) -> typing.Dict[str, str]:
        headers: typing.Dict[str, str] = {
            "X-Fern-Language": "Python",
            "X-Fern-SDK-Name": "seed",
            "X-Fern-SDK-Version": "0.0.0",
        }
        headers["X-API-KEY"] = self.custom_auth_scheme
        return headers


class SyncClientWrapper(BaseClientWrapper):
    def __init__(self, *, custom_auth_scheme: str, httpx_client: httpx.Client):
        super().__init__(custom_auth_scheme=custom_auth_scheme)
        self.httpx_client = httpx_client


class AsyncClientWrapper(BaseClientWrapper):
    def __init__(self, *, custom_auth_scheme: str, httpx_client: httpx.AsyncClient):
        super().__init__(custom_auth_scheme=custom_auth_scheme)
        self.httpx_client = httpx_client
