# This file was auto-generated by Fern from our API Definition.

import typing

import httpx


class BaseClientWrapper:
    def __init__(
        self,
        *,
        api_key: typing.Optional[typing.Callable[[str], typing.Callable[[], str]]] = None,
        api_secret: typing.Optional[typing.Callable[[str], typing.Callable[[], str]]] = None
    ):
        self._api_key = api_key
        self._api_secret = api_secret

    def get_headers(self) -> typing.Dict[str, str]:
        headers: typing.Dict[str, str] = {}
        headers["AUTHORIZATION"] = (httpx.BasicAuth(self._get_api_key(), self._get_api_secret())._auth_header,)
        return headers

    def _get_api_key(self) -> str:
        if isinstance(self._api_key, str):
            return self._api_key
        else:
            return self._api_key()

    def _get_api_secret(self) -> str:
        if isinstance(self._api_secret, str):
            return self._api_secret
        else:
            return self._api_secret()


class SyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        api_key: typing.Optional[typing.Callable[[str], typing.Callable[[], str]]] = None,
        api_secret: typing.Optional[typing.Callable[[str], typing.Callable[[], str]]] = None,
        httpx_client: httpx.Client
    ):
        super().__init__(api_key=api_key, api_secret=api_secret)
        self.httpx_client = httpx_client


class AsyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        api_key: typing.Optional[typing.Callable[[str], typing.Callable[[], str]]] = None,
        api_secret: typing.Optional[typing.Callable[[str], typing.Callable[[], str]]] = None,
        httpx_client: httpx.AsyncClient
    ):
        super().__init__(api_key=api_key, api_secret=api_secret)
        self.httpx_client = httpx_client
