# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .non_void_function_signature import NonVoidFunctionSignature
from .parameter import Parameter
from .parameter_id import ParameterId
from .void_function_signature import VoidFunctionSignature
from .void_function_signature_that_takes_actual_result import VoidFunctionSignatureThatTakesActualResult


class FunctionSignature_Void(VoidFunctionSignature):
    type: typing_extensions.Literal["void"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FunctionSignature_NonVoid(NonVoidFunctionSignature):
    type: typing_extensions.Literal["nonVoid"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FunctionSignature_VoidThatTakesActualResult(VoidFunctionSignatureThatTakesActualResult):
    type: typing_extensions.Literal["voidThatTakesActualResult"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


FunctionSignature = typing.Union[
    FunctionSignature_Void, FunctionSignature_NonVoid, FunctionSignature_VoidThatTakesActualResult
]
from .......commons.types.list_type import ListType  # noqa: E402
from .......commons.types.map_type import MapType  # noqa: E402
from .......commons.types.variable_type import VariableType  # noqa: E402
