# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from ...commons.types.binary_tree_node_value import BinaryTreeNodeValue
from ...commons.types.binary_tree_value import BinaryTreeValue
from ...commons.types.doubly_linked_list_node_value import DoublyLinkedListNodeValue
from ...commons.types.doubly_linked_list_value import DoublyLinkedListValue
from ...commons.types.node_id import NodeId
from ...commons.types.singly_linked_list_node_value import SinglyLinkedListNodeValue
from ...commons.types.singly_linked_list_value import SinglyLinkedListValue
from .actual_result import ActualResult
from .exception_info import ExceptionInfo
from .exception_v_2 import ExceptionV2
from .test_case_grade import TestCaseGrade
from .test_case_hidden_grade import TestCaseHiddenGrade
from .test_case_non_hidden_grade import TestCaseNonHiddenGrade
from .test_case_result import TestCaseResult
from .test_case_result_with_stdout import TestCaseResultWithStdout
from .traced_test_case import TracedTestCase


class SubmissionStatusForTestCase_Graded(TestCaseResultWithStdout):
    type: typing_extensions.Literal["graded"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class SubmissionStatusForTestCase_GradedV2(pydantic.BaseModel):
    type: typing_extensions.Literal["gradedV2"]
    value: TestCaseGrade

    class Config:
        frozen = True
        smart_union = True


class SubmissionStatusForTestCase_Traced(TracedTestCase):
    type: typing_extensions.Literal["traced"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


SubmissionStatusForTestCase = typing.Union[
    SubmissionStatusForTestCase_Graded, SubmissionStatusForTestCase_GradedV2, SubmissionStatusForTestCase_Traced
]
from ...commons.types.key_value_pair import KeyValuePair  # noqa: E402
from ...commons.types.map_value import MapValue  # noqa: E402
from ...commons.types.variable_value import VariableValue  # noqa: E402
