# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from ...commons.types.binary_tree_node_value import BinaryTreeNodeValue
from ...commons.types.binary_tree_value import BinaryTreeValue
from ...commons.types.doubly_linked_list_node_value import DoublyLinkedListNodeValue
from ...commons.types.doubly_linked_list_value import DoublyLinkedListValue
from ...commons.types.node_id import NodeId
from ...commons.types.singly_linked_list_node_value import SinglyLinkedListNodeValue
from ...commons.types.singly_linked_list_value import SinglyLinkedListValue
from .exception_info import ExceptionInfo
from .exception_v_2 import ExceptionV2
from .test_case_hidden_grade import TestCaseHiddenGrade
from .test_case_non_hidden_grade import TestCaseNonHiddenGrade


class TestCaseGrade_Hidden(TestCaseHiddenGrade):
    type: typing_extensions.Literal["hidden"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class TestCaseGrade_NonHidden(TestCaseNonHiddenGrade):
    type: typing_extensions.Literal["nonHidden"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


TestCaseGrade = typing.Union[TestCaseGrade_Hidden, TestCaseGrade_NonHidden]
from ...commons.types.key_value_pair import KeyValuePair  # noqa: E402
from ...commons.types.map_value import MapValue  # noqa: E402
from ...commons.types.variable_value import VariableValue  # noqa: E402
