# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from ...commons.types.binary_tree_node_value import BinaryTreeNodeValue
from ...commons.types.binary_tree_value import BinaryTreeValue
from ...commons.types.doubly_linked_list_node_value import DoublyLinkedListNodeValue
from ...commons.types.doubly_linked_list_value import DoublyLinkedListValue
from ...commons.types.node_id import NodeId
from ...commons.types.singly_linked_list_node_value import SinglyLinkedListNodeValue
from ...commons.types.singly_linked_list_value import SinglyLinkedListValue


class ProblemDescriptionBoard_Html(pydantic.BaseModel):
    type: typing_extensions.Literal["html"]
    value: str

    class Config:
        frozen = True
        smart_union = True


class ProblemDescriptionBoard_Variable(pydantic.BaseModel):
    type: typing_extensions.Literal["variable"]
    value: VariableValue

    class Config:
        frozen = True
        smart_union = True


class ProblemDescriptionBoard_TestCaseId(pydantic.BaseModel):
    type: typing_extensions.Literal["testCaseId"]
    value: str

    class Config:
        frozen = True
        smart_union = True


ProblemDescriptionBoard = typing.Union[
    ProblemDescriptionBoard_Html, ProblemDescriptionBoard_Variable, ProblemDescriptionBoard_TestCaseId
]
from ...commons.types.key_value_pair import KeyValuePair  # noqa: E402
from ...commons.types.map_value import MapValue  # noqa: E402
from ...commons.types.variable_value import VariableValue  # noqa: E402
