version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  check:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Type check
          command: poetry run mypy
      - run:
          name: pre-commit
          command: poetry run pre-commit run --all-files

workflows:
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
