version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  check:
    docker:
      - image: cimg/python:3.8.16-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Type check
          command: poetry run mypy
      - run:
          name: pre-commit
          command: poetry run pre-commit run --all-files

  test:
    docker:
      - image: cimg/python:3.8.16-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest -sv

  publish-dockers:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Publish Pydantic Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            docker build -f ./docker/pydantic-model/Dockerfile -t pydantic-model:${projectVersion} .
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker tag pydantic-model:"$projectVersion" fernapi/fern-pydantic-model:"$projectVersion"
            docker push fernapi/fern-pydantic-model:"$projectVersion"
      - run:
          name: Publish FastAPI Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            docker build -f ./docker/fastapi/Dockerfile -t fastapi-server:${projectVersion} .
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker tag fastapi-server:"$projectVersion" fernapi/fern-fastapi-server:"$projectVersion"
            docker push fernapi/fern-fastapi-server:"$projectVersion"
      - run:
          name: Publish SDK Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            docker build -f ./docker/sdk/Dockerfile -t fern-python-sdk:${projectVersion} .
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker tag fern-python-sdk:"$projectVersion" fernapi/fern-python-sdk:"$projectVersion"
            docker push fernapi/fern-python-sdk:"$projectVersion"

workflows:
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish-dockers:
          filters:
            branches:
              only: main
            tags:
              only:
                - /.*/
          requires:
            - check
            - test
          context:
            - docker-hub
