version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  check:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Type check
          command: poetry run mypy
      - run:
          name: pre-commit
          command: poetry run pre-commit run --all-files

  publish-docker:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          command: |
            projectVersion=$(./scripts/git-version.sh)
            docker build -f ./docker/pydantic-model/Dockerfile -t pydantic-model:${projectVersion}  .
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker tag pydantic-model:"$projectVersion" fernapi/fern-pydantic-model:"$projectVersion"
            docker push fernapi/fern-pydantic-model:"$projectVersion"


workflows:
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
      - publish-docker:
          filters:
            # branches:
            #   only: main
            tags:
              only: /.*/
          requires:
            - check
          context:
            - docker-hub
