# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from ..commons.binary_tree_node_value import BinaryTreeNodeValue
from ..commons.binary_tree_value import BinaryTreeValue
from ..commons.doubly_linked_list_node_value import DoublyLinkedListNodeValue
from ..commons.doubly_linked_list_value import DoublyLinkedListValue
from ..commons.node_id import NodeId
from ..commons.singly_linked_list_node_value import SinglyLinkedListNodeValue
from ..commons.singly_linked_list_value import SinglyLinkedListValue
from .exception_info import ExceptionInfo
from .exception_v_2 import ExceptionV2
from .test_case_hidden_grade import TestCaseHiddenGrade
from .test_case_non_hidden_grade import TestCaseNonHiddenGrade


class TestCaseGrade_Hidden(TestCaseHiddenGrade):
    type: typing_extensions.Literal["hidden"]

    class Config:
        allow_population_by_field_name = True


class TestCaseGrade_NonHidden(TestCaseNonHiddenGrade):
    type: typing_extensions.Literal["nonHidden"]

    class Config:
        allow_population_by_field_name = True


TestCaseGrade = typing.Union[TestCaseGrade_Hidden, TestCaseGrade_NonHidden]
from ..commons.key_value_pair import KeyValuePair  # noqa: E402
from ..commons.map_value import MapValue  # noqa: E402
from ..commons.variable_value import VariableValue  # noqa: E402
