# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from ..commons.binary_tree_node_value import BinaryTreeNodeValue
from ..commons.binary_tree_value import BinaryTreeValue
from ..commons.doubly_linked_list_node_value import DoublyLinkedListNodeValue
from ..commons.doubly_linked_list_value import DoublyLinkedListValue
from ..commons.node_id import NodeId
from ..commons.singly_linked_list_node_value import SinglyLinkedListNodeValue
from ..commons.singly_linked_list_value import SinglyLinkedListValue
from ..v_2.resources.problem.test_case_id import TestCaseId
from .compile_error import CompileError
from .error_info import ErrorInfo
from .exception_info import ExceptionInfo
from .exception_v_2 import ExceptionV2
from .graded_test_case_update import GradedTestCaseUpdate
from .internal_error import InternalError
from .recorded_test_case_update import RecordedTestCaseUpdate
from .running_submission_state import RunningSubmissionState
from .runtime_error import RuntimeError
from .test_case_grade import TestCaseGrade
from .test_case_hidden_grade import TestCaseHiddenGrade
from .test_case_non_hidden_grade import TestCaseNonHiddenGrade


class TestSubmissionUpdateInfo_Running(pydantic.BaseModel):
    type: typing_extensions.Literal["running"]
    value: RunningSubmissionState


class TestSubmissionUpdateInfo_Stopped(pydantic.BaseModel):
    type: typing_extensions.Literal["stopped"]


class TestSubmissionUpdateInfo_Errored(pydantic.BaseModel):
    type: typing_extensions.Literal["errored"]
    value: ErrorInfo


class TestSubmissionUpdateInfo_GradedTestCase(GradedTestCaseUpdate):
    type: typing_extensions.Literal["gradedTestCase"]

    class Config:
        allow_population_by_field_name = True


class TestSubmissionUpdateInfo_RecordedTestCase(RecordedTestCaseUpdate):
    type: typing_extensions.Literal["recordedTestCase"]

    class Config:
        allow_population_by_field_name = True


class TestSubmissionUpdateInfo_Finished(pydantic.BaseModel):
    type: typing_extensions.Literal["finished"]


TestSubmissionUpdateInfo = typing.Union[
    TestSubmissionUpdateInfo_Running,
    TestSubmissionUpdateInfo_Stopped,
    TestSubmissionUpdateInfo_Errored,
    TestSubmissionUpdateInfo_GradedTestCase,
    TestSubmissionUpdateInfo_RecordedTestCase,
    TestSubmissionUpdateInfo_Finished,
]
from ..commons.key_value_pair import KeyValuePair  # noqa: E402
from ..commons.map_value import MapValue  # noqa: E402
from ..commons.variable_value import VariableValue  # noqa: E402
