# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from ....commons.language import Language
from .assert_correctness_check import AssertCorrectnessCheck
from .deep_equality_correctness_check import DeepEqualityCorrectnessCheck
from .function_implementation import FunctionImplementation
from .function_implementation_for_multiple_languages import FunctionImplementationForMultipleLanguages
from .non_void_function_definition import NonVoidFunctionDefinition
from .non_void_function_signature import NonVoidFunctionSignature
from .parameter import Parameter
from .parameter_id import ParameterId
from .test_case_function import TestCaseFunction
from .test_case_implementation import TestCaseImplementation
from .test_case_implementation_description import TestCaseImplementationDescription
from .test_case_implementation_description_board import TestCaseImplementationDescriptionBoard
from .test_case_template_id import TestCaseTemplateId
from .test_case_with_actual_result_implementation import TestCaseWithActualResultImplementation
from .void_function_definition import VoidFunctionDefinition
from .void_function_definition_that_takes_actual_result import VoidFunctionDefinitionThatTakesActualResult


class TestCaseImplementationReference_TemplateId(pydantic.BaseModel):
    type: typing_extensions.Literal["templateId"]
    value: TestCaseTemplateId


class TestCaseImplementationReference_Implementation(TestCaseImplementation):
    type: typing_extensions.Literal["implementation"]

    class Config:
        allow_population_by_field_name = True


TestCaseImplementationReference = typing.Union[
    TestCaseImplementationReference_TemplateId, TestCaseImplementationReference_Implementation
]
from ....commons.list_type import ListType  # noqa: E402
from ....commons.map_type import MapType  # noqa: E402
from ....commons.variable_type import VariableType  # noqa: E402
