# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from ..commons.binary_tree_node_value import BinaryTreeNodeValue
from ..commons.binary_tree_value import BinaryTreeValue
from ..commons.doubly_linked_list_node_value import DoublyLinkedListNodeValue
from ..commons.doubly_linked_list_value import DoublyLinkedListValue
from ..commons.node_id import NodeId
from ..commons.singly_linked_list_node_value import SinglyLinkedListNodeValue
from ..commons.singly_linked_list_value import SinglyLinkedListValue


class ProblemDescriptionBoard_Html(pydantic.BaseModel):
    type: typing_extensions.Literal["html"]
    value: str


class ProblemDescriptionBoard_Variable(pydantic.BaseModel):
    type: typing_extensions.Literal["variable"]
    value: VariableValue


class ProblemDescriptionBoard_TestCaseId(pydantic.BaseModel):
    type: typing_extensions.Literal["testCaseId"]
    value: str


ProblemDescriptionBoard = typing.Union[
    ProblemDescriptionBoard_Html, ProblemDescriptionBoard_Variable, ProblemDescriptionBoard_TestCaseId
]
from ..commons.key_value_pair import KeyValuePair  # noqa: E402
from ..commons.map_value import MapValue  # noqa: E402
from ..commons.variable_value import VariableValue  # noqa: E402
