# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from ......commons.language import Language
from .deep_equality_correctness_check import DeepEqualityCorrectnessCheck
from .function_implementation import FunctionImplementation
from .function_implementation_for_multiple_languages import FunctionImplementationForMultipleLanguages
from .parameter import Parameter
from .parameter_id import ParameterId
from .void_function_definition_that_takes_actual_result import VoidFunctionDefinitionThatTakesActualResult


class AssertCorrectnessCheck_DeepEquality(DeepEqualityCorrectnessCheck):
    type: typing_extensions.Literal["deepEquality"]

    class Config:
        allow_population_by_field_name = True


class AssertCorrectnessCheck_Custom(VoidFunctionDefinitionThatTakesActualResult):
    type: typing_extensions.Literal["custom"]

    class Config:
        allow_population_by_field_name = True


AssertCorrectnessCheck = typing.Union[AssertCorrectnessCheck_DeepEquality, AssertCorrectnessCheck_Custom]
from ......commons.list_type import ListType  # noqa: E402
from ......commons.map_type import MapType  # noqa: E402
from ......commons.variable_type import VariableType  # noqa: E402
