# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from ......commons.language import Language
from .assert_correctness_check import AssertCorrectnessCheck
from .deep_equality_correctness_check import DeepEqualityCorrectnessCheck
from .function_implementation import FunctionImplementation
from .function_implementation_for_multiple_languages import FunctionImplementationForMultipleLanguages
from .non_void_function_definition import NonVoidFunctionDefinition
from .non_void_function_signature import NonVoidFunctionSignature
from .parameter import Parameter
from .parameter_id import ParameterId
from .test_case_with_actual_result_implementation import TestCaseWithActualResultImplementation
from .void_function_definition import VoidFunctionDefinition
from .void_function_definition_that_takes_actual_result import VoidFunctionDefinitionThatTakesActualResult


class TestCaseFunction_WithActualResult(TestCaseWithActualResultImplementation):
    type: typing_extensions.Literal["withActualResult"]

    class Config:
        allow_population_by_field_name = True


class TestCaseFunction_Custom(VoidFunctionDefinition):
    type: typing_extensions.Literal["custom"]

    class Config:
        allow_population_by_field_name = True


TestCaseFunction = typing.Union[TestCaseFunction_WithActualResult, TestCaseFunction_Custom]
from ......commons.list_type import ListType  # noqa: E402
from ......commons.map_type import MapType  # noqa: E402
from ......commons.variable_type import VariableType  # noqa: E402
