# This file was auto-generated by Fern from our API Definition.

import typing

import httpx

from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.custom_auth.client import AsyncCustomAuthClient, CustomAuthClient


class SeedCustomAuth:
    def __init__(self, *, environment: str, custom_auth_scheme: str, timeout: typing.Optional[float] = 60):
        self._environment = environment
        self._client_wrapper = SyncClientWrapper(
            custom_auth_scheme=custom_auth_scheme, httpx_client=httpx.Client(timeout=timeout)
        )
        self.custom_auth = CustomAuthClient(environment=environment, client_wrapper=self._client_wrapper)


class AsyncSeedCustomAuth:
    def __init__(self, *, environment: str, custom_auth_scheme: str, timeout: typing.Optional[float] = 60):
        self._environment = environment
        self._client_wrapper = AsyncClientWrapper(
            custom_auth_scheme=custom_auth_scheme, httpx_client=httpx.AsyncClient(timeout=timeout)
        )
        self.custom_auth = AsyncCustomAuthClient(environment=environment, client_wrapper=self._client_wrapper)
