# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.container.client import AsyncContainerClient, ContainerClient
from .resources.enum.client import AsyncEnumClient, EnumClient
from .resources.http_methods.client import AsyncHttpMethodsClient, HttpMethodsClient
from .resources.object.client import AsyncObjectClient, ObjectClient
from .resources.params.client import AsyncParamsClient, ParamsClient
from .resources.primitive.client import AsyncPrimitiveClient, PrimitiveClient
from .resources.union.client import AsyncUnionClient, UnionClient


class EndpointsClient:
    def __init__(self, *, environment: str, client_wrapper: SyncClientWrapper):
        self._environment = environment
        self._client_wrapper = client_wrapper
        self.container = ContainerClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.enum = EnumClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.http_methods = HttpMethodsClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.object = ObjectClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.params = ParamsClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.primitive = PrimitiveClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.union = UnionClient(environment=self._environment, client_wrapper=self._client_wrapper)


class AsyncEndpointsClient:
    def __init__(self, *, environment: str, client_wrapper: AsyncClientWrapper):
        self._environment = environment
        self._client_wrapper = client_wrapper
        self.container = AsyncContainerClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.enum = AsyncEnumClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.http_methods = AsyncHttpMethodsClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.object = AsyncObjectClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.params = AsyncParamsClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.primitive = AsyncPrimitiveClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.union = AsyncUnionClient(environment=self._environment, client_wrapper=self._client_wrapper)
